name: Lint & Build
on: [push, pull_request]

jobs:
  commit_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: lint
        run: npm run lint
